# render.yaml

services:
  - type: web
    name: fastapi-app
    env: python
    plan: free  # Choose "free" or upgrade if needed
    region: oregon  # Choose based on proximity to your users
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn my_app:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        sync: false  # Set to "true" if you want to sync with Render's environment dashboard
